### PR TITLE
Add setRequestHeader

### PR DESCRIPTION
**Pull request by olorin**
Sets a header to a value, replacing it if it already exists. This is a safe operation which is fiddly to implement with the current exposed interface (replacing a header in a valid request always results in a valid request, but removing a header from a valid request doesn't necessarily result in a valid request).

! @erikd-ambiata @thumphries

### CODE REVIEW

**Comment by olorin** [comment]
Anyone else up to having a look at this? Just realised I'm not sure when Erik and Tim' will be back. /cc @ambiata/engineers

**Comment by tmcgilchrist** [comment]
Only concern is whether things (other services) handle case-insensitive fields like the RFC's say they should.

The Eq instance of `HeaderName` looks like it does the right thing.

**Comment by olorin** [comment]
> Only concern is whether things (other services) handle case-insensitive fields like the RFC's say they should.

Maybe not; `hadron`'s only real job is to be compliant though, interacting with noncompliant services is a higher-level problem. Is there any potential behaviour in particular you're concerned about here which might cause problems?

**Comment by tmcgilchrist** [comment]
The behaviour here looks fine to me 🐫 on.

You're right handling non-compliance is a higher level concern, and perhaps not really an issue if we write all the services that interact.

**Pull request merged**
