### PR TITLE
Populate wai request path info

### PR DESCRIPTION
**Pull request by charleso**
! @olorin 

Something we hit in alice which was surprising.

/cc @nhibberd 
/jury approved @olorin @charleso

### CODE REVIEW

**Comment by olorin** [comment]
-nod- This seems reasonable; `decodePathSegments` should do the right thing with the representation from `renderRequestTarget`. Would you be okay with adding/extending a test to ensure that `requestTargetP` from Hadron.Core.Parser.Target can always parse `HT.encodePathSegments W.pathInfo` after converting a hadron request to a wai request? That seems like it should hold, maybe not necessary but I think it would be useful for clarity if nothing else.

**Comment by olorin** [comment]
:cat:

**Comment by olorin** [comment]
Taking over this PR/branch.

**Comment by olorin** [comment]
@charleso I think this is ready to go, want to give it a final review?

**Comment by charleso** [comment]
👍

**Pull request merged**
